# config.yaml

# Preprocessing parameters
pad: 300    # padding during cartesian -> polar (determines the max 2theta)
center: [33, 28]
pixel_size: 1.72e-4        # meters per pixel (172 µm) (pilatus detector)
wavelength: 35    # in kev

# Geometry parameters
detector_distance: 0.2383730470087054     # meters
N_theta: 100
min_two_theta: 0.0002
max_two_theta: 0
N_chi: 180
N_rot: 500
Nx: 148
Ny: 148
j_direction_0: [-1,0,0]
k_direction_0: [0,1,0]
p_direction_0: [0,0,1]
detector_direction_origin: [-1, 0, 0]
detector_direction_positive_90: [0, -1, 0]
cor_offset: -2

N_workers_integration: 12
factor_integration: 3
chunk_size_integration: 8

grid_resolution_parameter: 20
kernel_sigma: 0.07
peak_width: 0.003
reflection_cufoff: 0.15    # Only reflections with intensity >= reflection_cutoff * "maximum peak intensity" are saved

N_iter: 30


cif_path: "/dtu-compute/msaca/sliceA_diffraction/cif-files_and_theoretical_pd_spectra/Aluminum"
reflections_folder: "h5_files"

datapath: "/dtu/3d-imaging-center/projects/2025_QIM_BlackBeauty/raw_data_extern/raw/xrd_ct_overview/"
diffraction_file: "scan-0339_pilatus.h5"
absorption_file: "scan-0339_xspress3-dtc-2d.h5"
integrated_file: "/dtu-compute/msaca/danmax_2025/scan-0042_pilatus_integrated.h5"
B_matrix_path: "/work3/msaca/B_aluminum_small.h5"
reconstruction_file: "/work3/msaca/reconstructed_aluminum_small.h5"