# config.yaml

# Preprocessing parameters
pad: 300    # padding during cartesian -> polar (determines the max 2theta)
center: [33, 28]
pixel_size: 1.72e-4        # meters per pixel (172 µm) (pilatus detector)
wavelength: 34.798    # in kev

# Geometry parameters
detector_distance: 0.2383730470087054     # meters
N_theta: 5
min_two_theta: 0.0002
max_two_theta: 0.5
N_chi: 180
N_rot: 500
Nx: 148
Ny: 148
p_direction_0: [1,0,0] # bam axis
j_direction_0: [0,-1,0] # movement of the beam in the sample
k_direction_0: [0,0,1] # rotation axis
detector_direction_origin: [0, 1, 0]
detector_direction_positive_90: [0, 0, 1]
cor_offset: -2
angle_range: [0,360]

N_workers_integration: 12
factor_integration: 3
chunk_size_integration: 8

grid_resolution_parameter: 20
kernel_sigma: 0.07
peak_width: 0.003
reflection_cutoff: 0.15    # Only reflections with intensity >= reflection_cutoff * "maximum peak intensity" are saved

N_iter: 30


cif_path: "/dtu-compute/msaca/sliceA_diffraction/cif-files_and_theoretical_pd_spectra/Aluminum"

datapath: "/dtu/3d-imaging-center/projects/2025_QIM_BlackBeauty/raw_data_extern/raw_data_aluminum_detector/"
diffraction_files: ["scan-0048_pilatus.h5","scan-0049_pilatus.h5","scan-0050_pilatus.h5","scan-0051_pilatus.h5","scan-0052_pilatus.h5","scan-0053_pilatus.h5","scan-0054_pilatus.h5", "scan-0055_pilatus.h5", "scan-0056_pilatus.h5", "scan-0057_pilatus.h5", "scan-0058_pilatus.h5"]
reconstruction_file: "/work3/msaca/reconstructed_aluminum_small.h5"
poni_path: "/dtu/3d-imaging-center/projects/2025_QIM_BlackBeauty/raw_data_extern/raw_data_aluminum_detector/LaB6_34p798keV_244p89mm.poni"
integrated_file: "pilatus-0048-0058-integrated.h5"